# This is a basic workflow to help you get started with Actions

name: 'Core - TF - Validate'

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "test-core" branch
  push:
    paths:
      - Core/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: Core

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: Core
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend=false
      shell: bash

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform validate
      shell: bash
